theme_dpi_mapPNG<-
  function (base_size = 18, base_family = "") {
    require(gridExtra)
  structure(list(axis.line = theme_blank(), 
                 axis.text.x = theme_blank(), 
                 axis.text.y = theme_blank(), 
                 axis.ticks = theme_blank(), 
                 axis.title.x = theme_blank(), 
                 axis.title.y = theme_blank(), 
                 axis.ticks.length = unit(0.06, "cm"), 
                 axis.ticks.margin = unit(0.06, "cm"), 
                 legend.background = theme_rect(colour = "black"), 
                 legend.margin = unit(0.4, "cm"), 
                 legend.key = theme_rect(colour = "grey80"), 
                 legend.key.size = unit(1.3, "lines"), 
                 legend.key.height =NULL, 
                 legend.key.width = NULL, 
                 legend.text = theme_text(family = base_family, 
                                          size = base_size * 0.9), 
                 legend.text.align =NULL, 
                 legend.title = theme_text(family = base_family, 
                                           size = base_size * 1, 
                                           face = "bold", hjust = 0), 
                 legend.title.align = NULL, 
                 legend.position = c(.13,.15), 
                 legend.direction = 'vertical', 
                 legend.justification = "center", 
                 legend.box = NULL,
                 panel.background = theme_rect(fill = "white", colour = NA), 
                 panel.border = theme_rect(fill = NA, colour = NA), 
                 panel.grid.major = theme_blank(), 
                 panel.grid.minor = theme_blank(), 
                 panel.margin = unit(0.25, "lines"), 
                 strip.background = theme_rect(fill = "grey80", colour = "grey50"),
                 strip.text.x = theme_text(family = base_family, 
                                           size = base_size * 0.8), 
                 strip.text.y = theme_text(family = base_family, 
                                           size = base_size * 0.8, angle = -90), 
                 plot.background = theme_rect(colour = NA), 
                 plot.title = theme_text(family = base_family, size = base_size * 
                   1.4), face='bold',plot.margin = unit(c(1, 1, 0.5, 0.5), "lines")), 
            class = "options")
}